export const ADD_TO_CART = 'ADD_TO_CART';
export const UPDATE_CART_PRODUCT = 'UPDATE_CART_PRODUCTS';
export const DELETE_CART_PRODUCT = 'DELETE_CART_PRODUCT';
export const CLEAR_CART_PRODUCT = 'CLEAR_CART_PRODUCT';